export default {
  LOGIN: 'Login',
  ONBOARD: 'Onboard',
  OTP_SCREEN: 'OtpScreen',
  SIGNUP: 'SingUp',
  SIGNIN: 'Signin',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  PRIVACY_POLICY: 'PrivacyPolicy',
  TERM_CONDITION: 'TermCondition',

  HOME: 'Home',
  SETTING: 'Setting',
  GROUPS: 'Groups',
  FRIENDS: 'Friends',
  ACTIVITY: 'Activity',
  ACCOUNT: 'Account',
  ADDFRIEND: 'AddFriend',
  CREATEGRP: 'CreateGrp',
  ADDCONTACT: 'AddContact',
  VERIFYCONTACT: 'VerifyContact',
};
